// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgVpT4JMpUNbcG6riaf450WaIPDBAX8WA',
    appId: '1:760868798211:android:ee14b7d0ea123f8e0fb336',
    messagingSenderId: '760868798211',
    projectId: 'worldie-app',
    storageBucket: 'worldie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgpgek12OYk7AwdCk1UOZ6aSBTUjwA-kQ',
    appId: '1:760868798211:ios:2e2a7ff0abce9bb20fb336',
    messagingSenderId: '760868798211',
    projectId: 'worldie-app',
    storageBucket: 'worldie-app.appspot.com',
    iosClientId: '760868798211-490s285ao4fsva5g0cqu8ffq78sig3o2.apps.googleusercontent.com',
    iosBundleId: 'com.solvify.worldie',
  );
}
